### ISSUE TITLE
Index out of range when calling log methods with logger's name "xybor.xyplatform.main"

### ISSUE THREAD

**Issue by anhtoan1103** [xybor/xyplatform#42]
Version: v1.0.0
```
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/xybor/xyplatform/xylog.(*Logger).callHandlers(0xc0000841b0, {{0xc000026030, 0x23}, 0x62fdb1c8, {0x4e55f9, 0x7}, {0xc000018121, 0x4}, {0x4b142a, 0x5}, ...})
        /home/toto/go/pkg/mod/github.com/xybor/xyplatform@v1.0.0/xylog/logger.go:166 +0x154
github.com/xybor/xyplatform/xylog.(*Logger).handle(0xc0000841b0, {{0xc000026030, 0x23}, 0x62fdb1c8, {0x4e55f9, 0x7}, {0xc000018121, 0x4}, {0x4b142a, 0x5}, ...})
        /home/toto/go/pkg/mod/github.com/xybor/xyplatform@v1.0.0/xylog/logger.go:152 +0x87
github.com/xybor/xyplatform/xylog.(*Logger).log(0xc0000841b0, 0x8?, {0xc000018110, 0xb})
        /home/toto/go/pkg/mod/github.com/xybor/xyplatform@v1.0.0/xylog/logger.go:146 +0x105
github.com/xybor/xyplatform/xylog.(*Logger).Debug(0xc000070f70?, {0x4b1b17, 0x8}, {0xc000070f60, 0x1, 0x1})
        /home/toto/go/pkg/mod/github.com/xybor/xyplatform@v1.0.0/xylog/logger.go:82 +0x85
main.main()
        /home/toto/Golang/main/main.go:12 +0x6a
exit status 2
```

**Comment by huykingsofm** [comment]
I filed an internal ticket PLF-61 to track this issue.
